export const LIST_STATE = "LIST_STATE";
export const SINGLEITEM_STATE = "SINGLEITEM_STATE";
export const DESCRIPTION_STATE = "DESCRIPTION_STATE";
export const INCREMENT = "INCREMENT";
export const DECREMENT = "DECREMENT";


